### ISSUE TITLE
compilation error in kali linux

### ISSUE THREAD

**Issue by akshay1991raj** [HackerFantastic/Public#4]
getting the following error:

root@kali:/opt#  gcc -lssl -lssl3 -lcrypto heartbleed.c -o heartbleed
heartbleed.c:88:25: fatal error: openssl/bio.h: No such file or directory
 #include &lt;openssl/bio.h&gt;
                         ^
compilation terminated.

**Comment by L2008** [comment]
Hello, I have the same problem, any solution?

I'm using  Kali linux 2.0

**Comment by sagishahar** [comment]
As @HackerFantastic mentioned in [this](https://github.com/HackerFantastic/Public/issues/1) issue feed, use the following command:
```
$gcc heartbleed.c -o heartbleed -Wl,-Bstatic -lssl -Wl,-Bdynamic -lssl3 -lcrypto
$ uname -a
Linux X0 4.0.0-kali1-amd64 #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) x86_64 GNU/Linux
$ ls -al
-rwxr-xr-x  1 x x   369848 Feb 22 19:31 heartbleed
```

**Comment by HackerFantastic** [comment]
I assume this issue is now closed, there are various compile instructions for slightly different flavours of linux. Thank you.
